- name: Install and configure extrausers director
  hosts: directors
  become: true
  roles:
    - google-extrausers-director

# - name: Install and configure extrausers agents
#   hosts: agents
#   become: true
#   roles:
#     - extrausers_agent
